### Importando as bibliotecas

In [25]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### Fazendo a leitura dos dados e tirando as colunas que não serão utilizadas

In [26]:
standard_df = pd.read_csv('..\\data\\player-standard-stats.csv', index_col=0)
miscellaneous_df = pd.read_csv('..\\data\\player-miscellaneous-stats.csv', index_col=0)

In [27]:
standard_df.head()

,Player,Nation,Pos,Squad,Age,Born,MP,Starts,Min,90s,...,PKatt,CrdY,CrdR,Gls.1,Ast.1,G+A.1,G-PK.1,G+A-PK,Matches,-9999
Rk,,,,,,,,,,,,,,,,,,,,,
1,Abner,br BRA,DF,Juventude,20,2004,19,13,1318,14.6,...,0,3,0,0.00,0.07,0.07,0.00,0.07,Matches,6c0ef11c
2,Nicolás Acevedo,uy URU,MF,Bahia,25,1999,32,18,1690,18.8,...,0,6,0,0.00,0.05,0.05,0.00,0.05,Matches,6140be7b
3,Luciano Acosta,ar ARG,MF,Fluminense,30,1994,16,15,1199,13.3,...,0,5,0,0.23,0.15,0.38,0.23,0.38,Matches,363ba6d7
4,Adriel,br BRA,MF,Sport Recife,18,2006,5,1,148,1.6,...,0,1,0,0.00,0.00,0.00,0.00,0.00,Matches,959e965c
5,Adson,br BRA,MF,Vasco da Gama,24,2000,10,0,210,2.3,...,0,0,0,0.00,0.00,0.00,0.00,0.00,Matches,eda38706

In [28]:
miscellaneous_df.head()

,Player,Nation,Pos,Squad,Age,Born,90s,CrdY,CrdR,2CrdY,...,Fld,Off,Crs,Int,TklW,PKwon,PKcon,OG,Matches,-9999
Rk,,,,,,,,,,,,,,,,,,,,,
1,Abner,br BRA,DF,Juventude,20,2004,14.6,3,0,0,...,5,1,0,18,11,NaN,NaN,0,Matches,6c0ef11c
2,Nicolás Acevedo,uy URU,MF,Bahia,25,1999,18.8,6,0,0,...,28,0,10,30,42,NaN,NaN,0,Matches,6140be7b
3,Luciano Acosta,ar ARG,MF,Fluminense,30,1994,13.3,5,0,0,...,25,2,37,0,15,NaN,NaN,0,Matches,363ba6d7
4,Adriel,br BRA,MF,Sport Recife,18,2006,1.6,1,0,0,...,0,0,0,2,3,NaN,NaN,0,Matches,959e965c
5,Adson,br BRA,MF,Vasco da Gama,24,2000,2.3,0,0,0,...,3,0,7,0,3,NaN,NaN,0,Matches,eda38706

In [29]:
standard_df = standard_df.drop(columns=['Matches', '-9999'])
miscellaneous_df = miscellaneous_df.drop(columns=['Player', 'Nation', 'Pos', 'Squad', 'Age', 'Born', '90s', 'CrdY', 'CrdR', 'Matches', '-9999'])

### Fazendo o JOIN entre os dois csv's

In [30]:
stats_df = pd.merge(standard_df, miscellaneous_df, on='Rk', how='inner')

In [31]:
stats_df.head()

,Player,Nation,Pos,Squad,Age,Born,MP,Starts,Min,90s,...,2CrdY,Fls,Fld,Off,Crs,Int,TklW,PKwon,PKcon,OG
Rk,,,,,,,,,,,,,,,,,,,,,
1,Abner,br BRA,DF,Juventude,20,2004,19,13,1318,14.6,...,0,16,5,1,0,18,11,NaN,NaN,0
2,Nicolás Acevedo,uy URU,MF,Bahia,25,1999,32,18,1690,18.8,...,0,44,28,0,10,30,42,NaN,NaN,0
3,Luciano Acosta,ar ARG,MF,Fluminense,30,1994,16,15,1199,13.3,...,0,27,25,2,37,0,15,NaN,NaN,0
4,Adriel,br BRA,MF,Sport Recife,18,2006,5,1,148,1.6,...,0,7,0,0,0,2,3,NaN,NaN,0
5,Adson,br BRA,MF,Vasco da Gama,24,2000,10,0,210,2.3,...,0,2,3,0,7,0,3,NaN,NaN,0

In [33]:
stats_df.to_csv('..\\data\\player-stats.csv')